export enum Actions {
  DOG = 'dog',
  CAT = 'cat',
  HELP_MENU = 'help_menu',
  HELP_MENU_SCEBE = 'help_menu_scene',
  WEATHER = 'weather',
  GET_WEATHER = 'get_weather',
  SUBSCRIBE_WEATHER = 'subscribe_weather',
  GET_WEATHER_SUBSCRIBE = 'get_weather_subscribe',
  UNSUBSCRIBE_WEATHER = 'unsubscribe_weather',
  DELETE_TASK = 'delete_task',
  ADD_TASK = 'add_task',
  TASK = 'task',
  MY_TASK = 'my_task',
  SUBSCRIBE_TASK = 'subscribe_task',
  UN_SUBSCRIBE_TASK = 'un_subscribe_task',
  RECOMMEND_MENU = 'RECOMMEND_MENU',
  RECOMMEND_CAFE = 'RECOMMEND_EVENTS',
  RECOMMEND_ATTRACTIONS = 'RECOMMEND_PLACE',
  RECOMMEND_THEATRES_AND_ENTERTAINMENTS = 'theatres_and_entertainments',
  RECOMMEND_SHOPS = 'shops',
  RECOMMEND_BANK = 'banks'
}
